AWSTemplateFormatVersion: 2010-09-09
Parameters:



  Env:
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - stg
      - dev
  SystemName:
    Type: String
    Default: web
    AllowedPattern: ^web$
  NetworkStack:
    Type: String

  WebStack:
    Type: String

  ImageId:
    Type: AWS::EC2::Image::Id
  AlbCidr:
    Type: String
    AllowedPattern: ^(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/([1-2]?[0-9]|3[0-2])$
    Default: 0.0.0.0/0

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Metadata
        Parameters:
          - Env
          - SystemName
      - Label:
          default: Dependent Stacks
        Parameters:
          - NetworkStack

Resources:

  SgBastionInstance:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-${Env}-bastion-instance-sg
      GroupDescription: !Sub ${SystemName}-${Env}-instance-sg
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStack}-Vpc
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: inbound for ssh
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-instance-sg


 